### PR TITLE
Saumya and Nekesa Project Submission

### PR DESCRIPTION
**Pull request by kesamercy**

### CODE REVIEW

**Comment by yjzhux** [comment]
Not master branch.

**Comment by kesamercy** [comment]
What do you mean not master branch? SHould we resubmit again?

Kind Regards,
Mercy Nekesa

**Comment by yjzhux** [comment]
You request is to merge your code to the master branch of the public repo, which is not allowed. Please refer to README.md (step 4) to merge to **your own branch**.

**Comment by kesamercy** [comment]
Okay, tried resubmitting again.

Does what I have look fine?

Kind Regards,
Mercy Nekesa

**Pull request closed without merging**
